// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyx_uubI3c_-miUpqJ_MG1WIGVmWIcpo',
    appId: '1:986011727901:web:199c4920644b31e3246ef4',
    messagingSenderId: '986011727901',
    projectId: 'chat-app1-7a8b7',
    authDomain: 'chat-app1-7a8b7.firebaseapp.com',
    storageBucket: 'chat-app1-7a8b7.appspot.com',
    measurementId: 'G-DDSYK6DSY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-Pvn6nHVhdaEo651_alTnmYp9yWqYxk',
    appId: '1:986011727901:android:87f35b9417a7bd6b246ef4',
    messagingSenderId: '986011727901',
    projectId: 'chat-app1-7a8b7',
    storageBucket: 'chat-app1-7a8b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cmSopNnsFCA5wP0KQTSJTXCdQKmepnM',
    appId: '1:986011727901:ios:9b281d47ce3ec9e1246ef4',
    messagingSenderId: '986011727901',
    projectId: 'chat-app1-7a8b7',
    storageBucket: 'chat-app1-7a8b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9cmSopNnsFCA5wP0KQTSJTXCdQKmepnM',
    appId: '1:986011727901:ios:9b281d47ce3ec9e1246ef4',
    messagingSenderId: '986011727901',
    projectId: 'chat-app1-7a8b7',
    storageBucket: 'chat-app1-7a8b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbyx_uubI3c_-miUpqJ_MG1WIGVmWIcpo',
    appId: '1:986011727901:web:d817dec4c47f040a246ef4',
    messagingSenderId: '986011727901',
    projectId: 'chat-app1-7a8b7',
    authDomain: 'chat-app1-7a8b7.firebaseapp.com',
    storageBucket: 'chat-app1-7a8b7.appspot.com',
    measurementId: 'G-82S4W5Q4V0',
  );
}
